//creamos una variable
@api = http://localhost:3000/productos


GET {{api}}

###
POST {{api}}
//aqui le decimos que mandamos un objeto json
Content-Type: application/json

{
  "Nombre": "Mesa",
  "Descripcion": "alpaca",
  "Cantidad": 15
}

###
GET {{api}}/4

### 
DELETE {{api}}/3

###
GET {{api}}/count

###
PUT {{api}}/4
Content-Type: application/json

{
  "Nombre": "Mesa",
  "Descripcion": "una",
  "Cantidad": 25
}


