//creamos una variable
@api = http://localhost:3000/productos


GET {{api}}

###
POST {{api}}
//aqui le decimos que mandamos un objeto json
Content-Type: application/json

{
  "Nombre": "ropero",
  "Descripcion": "alpaca",
  "Cantidad": 5
}

###
GET {{api}}/5

### 
DELETE {{api}}/4

###
GET {{api}}/count

###
PUT {{api}}/5
Content-Type: application/json

{
  "Nombre": "cama",
  "Descripcion": "dos plazas",
  "Cantidad": 25
}


