//creamos una variable
@api = http://localhost:3000/productos


GET {{api}}

###
POST {{api}}
//aqui le decimos que mandamos un objeto json
Content-Type: application/json

{
  "Nombre": "esquinero",
  "Descripcion": "madera",
  "Cantidad": 15
}

###
GET {{api}}/

### 
DELETE {{api}}/24

###
GET {{api}}/count

###
PUT {{api}}/15
Content-Type: application/json

{
  "Nombre": "poltrona",
  "Descripcion": "cuero ecologico",
  "Cantidad": 35
}


